### ISSUE TITLE
Make `autotag_creator` suppressible

### ISSUE THREAD

**Issue by jangroth** [GorillaStack/auto-tag#78]
Firstly, thanks for this amazing tool. It saved me many hours of implementing similar functionality!

It would be great if all autotags were suppressible. ATM, only these are:

```
  AutoTagTagsCreateTime:
    Description: Enable/Disable the "CreateTime" tagging for all resources.

  AutoTagTagsInvokedBy:
    Description: Enable/Disable the "InvokedBy" tagging for all resources.
```
