### ISSUE TITLE
Don't hard code role names in the lambda

### ISSUE THREAD

**Issue by jangroth** [GorillaStack/auto-tag#79]
I'm working in an environment where we use naming conventions to indicate ownership (in addition to tagging). 

Would love the ability to prefix autotag's role paths like so:

```
  AutoTagMasterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: "${AWS::StackName}"
...
      Path: "/xyz/gorillastack/autotag/master/"
```

Unfortunately this is also hard coded in the lambda:
```
const MASTER_ROLE_PATH = '/gorillastack/autotag/master/';

class AutotagDefaultWorker {
...
```

It would be great if the role path would be passed into the lambda. This would make CFN the only source of truth and thereby not require to rebuild the lambda.
